org: danf338
app: exabeam-sent

service: exabeam

provider:
  name: aws
  runtime: python3.8
package:
    include:
        - ./*.py
functions:
  analyse:
    handler: handler.analyse
    events:
        - http:
            path: users/create
            method: get
